
title: The Back Room
baseurl: ""
url: "https://the-back-room.info"

remote_theme: "just-the-docs/just-the-docs"

color_scheme: dracula

social_image: "{{ page.social_image }}"

favicon_ico: "/assets/images/favicon.ico"

keywords:
  - open-source
  - development
  - software tweaks
  - graphic design
  - windows themes
  - customization
  - comics and doujinshi

permalink: pretty

search_enabled: true
search.button: true
search.previews: 3
search.preview_words_after: 10
search.tokenizer_separator: /[\s/]+/
search:
    focus_shortcut_key: 'k'

heading_anchors: true

mermaid:
  version: "9.1.6"

liquid:
  error_mode: strict
  strict_filters: true

callouts_level: quiet
callouts:
  highlight:
    color: yellow
    appearance: minimal
  important:
    color: blue
    appearance: minimal
  new:
    color: green
    appearance: minimal
  note:
    color: purple
    appearance: minimal
  warning:
    color: red
    appearance: minimal

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [] 
  blanklines: false
  profile: false